#!/bin/bash

if [ -z $_PS1 ]; then
  export _OLD_PATH=$PATH
  export PATH=`pwd`/python2.7/bin:$PATH
  export _PS1=$PS1
  export PS1=(python2.7)$PS1
fi

function deactivate(){
  export PATH=$_OLD_PATH
  unset _OLD_PATH
  export PS1=$_PS1
  unset _PS1
  unset -f deactivate
}
