# -*- coding: utf-8 -*-
__all__ = ['HOST', 'REQ_PORT', 'RES_PORT', 'CHA_PORT', 'HEARTBEATTIME', 'HEARTBEAT', 'WORKERTIME', 'FINDONE',
           'SENDBLOCK', 'SENDNOBLOCK', 'OK', 'NO', 'TIMEOUT', 'DEMANDTIMEOUT', 'FINDTIMEOUT', 'DISPOSETIMEOUT',
           'GETLIST', 'GETTOTAL']

HEARTBEATTIME = 25
# worker心跳时间
HEARTBEAT = b'HELLO'
# worker心跳消息
WORKERTIME = 30
# worker心跳超时时间

FINDONE = b'FIND'
SENDBLOCK = b'REQUEST'
SENDNOBLOCK = b'SEND'
GETLIST = b'GETLIST'
GETTOTAL = b'GETSUM'
# 请求指令

OK = b'OK'
NO = b'NO'
TIMEOUT = b'TIMEOUT'
# 回应状态

DEMANDTIMEOUT = 30
# 请求的超时时间
FINDTIMEOUT = 5
# 查找设备超时
DISPOSETIMEOUT = 25
# 处理的超时时间要小于请求时间
